/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import dao.ExtraDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Extra;

/**
 *
 * @author italo
 */
public class Frm_escolherExtra extends javax.swing.JFrame {

    private ExtraDAO extradao;
    private Frm_cadastroQuarto atual;
    
    public Frm_escolherExtra(Frm_cadastroQuarto tela) {
        initComponents();
        extradao = new ExtraDAO();
        atual = tela;
        preencherTabela();
    }

    private void preencherTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_extra.getModel();
        try {
           ArrayList<Extra> extras = extradao.read();

            for(Extra x : extras) {
                String[] dados = new String[2];
                dados[0] = x.getId() + "";
                dados[1] = x.getNome();
                modelo.addRow(dados);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_extra = new javax.swing.JTable();
        btEscolher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tbl_extra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Extra"
            }
        ));
        jScrollPane1.setViewportView(tbl_extra);

        btEscolher.setText("Escolher");
        btEscolher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEscolherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btEscolher))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btEscolher)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(376, 321));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEscolherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEscolherActionPerformed
        // TODO add your handling code here:
        int linha = tbl_extra.getSelectedRow();
        if (linha != -1) {
            String id = (String) tbl_extra.getValueAt(linha, 0);
            String extra = (String) tbl_extra.getValueAt(linha, 1);
            atual.inserirExtra(id, extra);
        }

    }//GEN-LAST:event_btEscolherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEscolher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_extra;
    // End of variables declaration//GEN-END:variables
}
