/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author darkc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastroHospede = new javax.swing.JButton();
        btCadastraProduto = new javax.swing.JButton();
        btCadastraQuarto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btReservaQuarto = new javax.swing.JButton();
        btPedido = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btCadastroHospede.setText("Cadastrar hospede");
        btCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastroHospede);
        btCadastroHospede.setBounds(10, 11, 137, 39);

        btCadastraProduto.setText("Cadastrar produto");
        btCadastraProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastraProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastraProduto);
        btCadastraProduto.setBounds(10, 68, 137, 39);

        btCadastraQuarto.setText("Cadastrar quarto");
        btCadastraQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastraQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastraQuarto);
        btCadastraQuarto.setBounds(10, 113, 137, 39);

        jButton1.setText("Consulta 1");
        getContentPane().add(jButton1);
        jButton1.setBounds(371, 19, 83, 23);

        jButton2.setText("Consulta 2");
        getContentPane().add(jButton2);
        jButton2.setBounds(371, 61, 83, 23);

        jButton3.setText("Consulta 3");
        getContentPane().add(jButton3);
        jButton3.setBounds(371, 95, 83, 23);

        jButton4.setText("Consulta 4");
        getContentPane().add(jButton4);
        jButton4.setBounds(371, 129, 83, 23);

        jButton5.setText("Consulta 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(371, 158, 83, 23);

        jButton6.setText("Consulta 6");
        getContentPane().add(jButton6);
        jButton6.setBounds(371, 192, 83, 23);

        jButton7.setText("Consulta 7");
        getContentPane().add(jButton7);
        jButton7.setBounds(371, 226, 83, 23);

        btReservaQuarto.setText("Reservar quarto");
        getContentPane().add(btReservaQuarto);
        btReservaQuarto.setBounds(10, 158, 137, 39);

        btPedido.setText("Pedido");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btPedido);
        btPedido.setBounds(10, 260, 137, 40);

        jButton8.setText("Cadastrar funcionario");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 208, 137, 41);

        setSize(new java.awt.Dimension(505, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroHospedeActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroHospede().setVisible(true);
    }//GEN-LAST:event_btCadastroHospedeActionPerformed

    private void btCadastraProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastraProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCadastraProdutoActionPerformed

    private void btCadastraQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastraQuartoActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroQuarto().setVisible(true);
        
    }//GEN-LAST:event_btCadastraQuartoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        // TODO add your handling code here:
        new Frm_pedido().setVisible(true);
    }//GEN-LAST:event_btPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastraProduto;
    private javax.swing.JButton btCadastraQuarto;
    private javax.swing.JButton btCadastroHospede;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btReservaQuarto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
