/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import bd.Conexao;
import java.sql.Connection;
import javax.swing.JOptionPane;
import model.Funcionario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author darkc
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Funcionario logado;
    
    public Principal(Funcionario f) {
        initComponents();
        logado = f;
        
        if(logado != null){
            lblLogado.setText(logado.getCargo());
        }else{
            lblLogado.setText("admin");
        }
        this.verificaLogado();
    }

    private void verificaLogado(){
        if(logado != null && logado.getCargo().equalsIgnoreCase("atendente")){
            this.btCadastraProduto.setEnabled(false);
            this.btCadastraQuarto.setEnabled(false);
            this.btReservaQuarto.setEnabled(false);
            this.btRelatorio.setEnabled(false);
            this.btCadastroHospede.setEnabled(false);
            this.btCadastrarFuncionrio.setEnabled(false);
        }else if(logado != null && logado.getCargo().equalsIgnoreCase("recepcionista")){
             this.btCadastraProduto.setEnabled(false);
            this.btCadastraQuarto.setEnabled(false);
            this.btRelatorio.setEnabled(false);
            this.btPedido.setEnabled(false);
            this.btCadastrarFuncionrio.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastroHospede = new javax.swing.JButton();
        btCadastraProduto = new javax.swing.JButton();
        btCadastraQuarto = new javax.swing.JButton();
        btReservaQuarto = new javax.swing.JButton();
        btPedido = new javax.swing.JButton();
        btCadastrarFuncionrio = new javax.swing.JButton();
        lblLogado = new javax.swing.JLabel();
        btRelatorio = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btCadastroHospede.setText("Cadastrar hospede");
        btCadastroHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroHospedeActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastroHospede);
        btCadastroHospede.setBounds(10, 11, 137, 39);

        btCadastraProduto.setText("Cadastrar produto");
        btCadastraProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastraProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastraProduto);
        btCadastraProduto.setBounds(10, 68, 137, 39);

        btCadastraQuarto.setText("Cadastrar quarto");
        btCadastraQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastraQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastraQuarto);
        btCadastraQuarto.setBounds(10, 113, 137, 39);

        btReservaQuarto.setText("Reservar quarto");
        btReservaQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservaQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btReservaQuarto);
        btReservaQuarto.setBounds(10, 158, 137, 39);

        btPedido.setText("Pedido");
        btPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btPedido);
        btPedido.setBounds(10, 260, 137, 40);

        btCadastrarFuncionrio.setText("Cadastrar funcionario");
        btCadastrarFuncionrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarFuncionrioActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarFuncionrio);
        btCadastrarFuncionrio.setBounds(10, 208, 137, 41);
        getContentPane().add(lblLogado);
        lblLogado.setBounds(340, 280, 140, 40);

        btRelatorio.setText("Relatório");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btRelatorio);
        btRelatorio.setBounds(240, 10, 100, 40);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 260, 110, 40);

        setSize(new java.awt.Dimension(505, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastroHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroHospedeActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroHospede().setVisible(true);
    }//GEN-LAST:event_btCadastroHospedeActionPerformed

    private void btCadastraProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastraProdutoActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroProduto().setVisible(true);
    }//GEN-LAST:event_btCadastraProdutoActionPerformed

    private void btCadastraQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastraQuartoActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroQuarto().setVisible(true);
        
    }//GEN-LAST:event_btCadastraQuartoActionPerformed

    private void btCadastrarFuncionrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarFuncionrioActionPerformed
        // TODO add your handling code here:
        new Frm_cadastroFuncionario().setVisible(true);
    }//GEN-LAST:event_btCadastrarFuncionrioActionPerformed

    private void btPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPedidoActionPerformed
        // TODO add your handling code here:
        new Frm_pedido(logado).setVisible(true);
    }//GEN-LAST:event_btPedidoActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        // TODO add your handling code here:
        int respost = JOptionPane.showConfirmDialog(null, "Deseja visualizar o relatório?");
        if (respost == JOptionPane.YES_OPTION) {
            Conexao conexao = new Conexao();
            Connection con = conexao.conectar();
            String caminho = "relatorio.jasper";
            JasperPrint jasper = null;
            try {
                jasper = JasperFillManager.fillReport(caminho, null, con);
                JasperViewer view = new JasperViewer(jasper, false);
                view.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao gerar relatório. "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btRelatorioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Frm_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btReservaQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservaQuartoActionPerformed
        // TODO add your handling code here:
        new Frm_reserva(logado).setVisible(true);
        
    }//GEN-LAST:event_btReservaQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastraProduto;
    private javax.swing.JButton btCadastraQuarto;
    private javax.swing.JButton btCadastrarFuncionrio;
    private javax.swing.JButton btCadastroHospede;
    private javax.swing.JButton btPedido;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btReservaQuarto;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lblLogado;
    // End of variables declaration//GEN-END:variables
}
